# Generated by Django 2.1.5 on 2021-03-16 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useruniquetoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useruniquetoken',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
