version: "3"

services:
  dj:
    network_mode: "host"
    container_name: dj
    build: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django:/code
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS=dev
  ng:
    container_name: ng
    build: angular
    ports:
      - "80:80"
