version: "3"

services:
  django-service:
    container_name: django-container
    build: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django:/code
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS=dev
  angular-service:
    container_name: angular-container
    build: angular
    ports:
      - "80:80"
