# Generated by Django 2.1.5 on 2023-03-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KPI_HT_TRANS',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField(null=True)),
                ('prix_HT', models.CharField(blank=True, max_length=200, null=True)),
                ('is_deleted', models.BooleanField(null=True)),
                ('type_service', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
