# Generated by Django 2.1.5 on 2022-09-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carburant',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code_Carburant', models.CharField(blank=True, max_length=200, null=True)),
                ('type_Carburant', models.CharField(blank=True, max_length=200, null=True)),
                ('dateupdate', models.DateField(null=True)),
                ('prix_essence', models.CharField(blank=True, max_length=200, null=True)),
                ('prix_Diesel', models.CharField(blank=True, max_length=200, null=True)),
                ('prix_Gaz', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entretien',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code_Entretien', models.CharField(blank=True, max_length=200, null=True)),
                ('dateupdate', models.DateField(null=True)),
                ('prix_entretien', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndiceCarburant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_IndiceCarburant', models.CharField(blank=True, max_length=200, null=True)),
                ('dateupdate', models.DateField(null=True)),
                ('prix_IndiceCarburant', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pneumatique',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code_Pneumatique', models.CharField(blank=True, max_length=200, null=True)),
                ('dateupdate', models.DateField(null=True)),
                ('prix_Pneumatique', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
